displayName=Trim Sails Notifier
author=big juice
support=https://github.com/bigjuiceee
description=Notifies you when the "Trim sails" option becomes available
plugins=com.trimsails.TrimSailsNotifierPlugin
